<?php
namespace backend\api\controllers;

use yii\rest\ActiveController;
//devolve todas as refeiçoes  inseridas na base de dados

class MealController extends ActiveController
{
    public function actions()//desativa todas as funçoes desnecessarias para o utilizador, deixa apenas o get disponivel
    {
        $action= parent::actions(); // TODO: Change the autogenerated stub
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
        return $action;
    }

    public $modelClass ='app\models\Meals';
}